maxIteration : 1000
particleNumber : 500
gamma : 1.0
alpha : 1.0
beta : 2.0
zeta : 2.0
bound:
  upper : [4.0,4.0]
  lower : [0.0,0.0]
  startVelocityMax : [1.0,1.0]

QuadraticOptimization:
    H : [1,0, 0,2]
    f : [1,0]
    E : [2.0,1.0]
    d : [1.0]
    A : [2.0,1.0 ,1.0,0.5]
    b : [1.0,2.0]
